apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: myapp
  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: hello
        image: gcr.io/apt-reality-357605/test@sha256:94ba4bc523ec4a73da7d41c072c42a85cfcaaf23426263ee4852939b094dcbdd
        ports:
        - containerPort: 5000




