apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: myapp
  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: hello
        image: gcr.io/apt-reality-357605/test@sha256:32cdcaa082fcd2319c1c406c7e2dcc97d8692b542871acedef57141cb526fe56:latest 
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
             number: 8080
        
