apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: myapp
  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: hello
        image: gcr.io/apt-reality-357605/test@sha256:d6217f1836f3202d34ef036079e532cf78dfb7f18d662367797535eb7d6136cf
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello
          servicePort: 8080
