apiVersion: v1
kind: Pod
metadata: 
  name: kaniko
spec: 
  containers: 
    - 
      args: 
        - "--context=git://github.com/scriptcamp/kubernetes-kaniko"
        - "--destination=devdatta1987/hello-kaniko:1.0"
      image: "gcr.io/kaniko-project/executor:debug"
      name: kaniko
      resources:   
        requests: 
          cpu: 250m
          memory: 256Mi
        limits: 
          cpu: 500m
          memory: 512Mi
      volumeMounts: 
        - 
          mountPath: /kaniko/.docker
          name: kaniko-secret
  restartPolicy: Never
  volumes: 
    - 
      name: kaniko-secret
      secret: 
        items: 
          - 
            key: .dockerconfigjson
            path: config.json
        secretName: dockercred
